---
title: "Data-Explore"
author: "Vanessa Tobias <vanessadtobias@gmail.com>"
date: "7/27/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load the libraries
```{r}
library(ggplot2)
library(cowplot)
```

# Set up the data
We just want to use 2010 data for now because it includes the largest number of variables. We also want to fill in the elevation for all years.

```{r}

master <- read.csv("master.csv", header = TRUE, stringsAsFactors = FALSE)
master2010 <- master[master$year == 2010,]
```

# Make some plots
```{r multiple plot function}
# Multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
#http://www.cookbook-r.com/Graphs/Multiple_graphs_on_one_page_(ggplot2)/

multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```


```{r}
p1 <- ggplot(master2010, aes(SoCI_bond, pop_change1)) +
  geom_point() +
  geom_hline(yintercept = 0) +
  theme_cowplot() +
  xlab("Bonding") +
  ylab("Population Change (%)")
p2 <- ggplot(master2010, aes(SoCI_bridge, pop_change1)) +
  geom_point() +
  geom_hline(yintercept = 0) +
  theme_cowplot() +
  xlab("Bridging") +
  ylab("Population Change (%)")
p3 <- ggplot(master2010, aes(SoCI_bond, pop_change2)) +
  geom_point() +
  geom_hline(yintercept = 0) +
  theme_cowplot() +
  xlab("Bonding") +
  ylab("Population Change (%)")
p4 <- ggplot(master2010, aes(SoCI_bridge, pop_change2)) +
  geom_point() +
  geom_hline(yintercept = 0) +
  theme_cowplot() +
  xlab("Bridging") +
  ylab("Population Change (%)")
multiplot(p1, p3, p2, p4, cols=2)
```

